### ISSUE TITLE
Installation Issue: Ubuntu 20.04

### ISSUE THREAD

**Issue by BirBDey** [galaunay/pypyueye#3]
Hi,
I tried installing using pip, I get the following warning messages when I try to import it:
```
Traceback (most recent call last):
  File "/home/bikram/.local/lib/python3.8/site-packages/pyueye/dll.py", line 166, in load_dll
    dll = DLL(libinfo, libnames, os.getenv(envname))
  File "/home/bikram/.local/lib/python3.8/site-packages/pyueye/dll.py", line 96, in __init__
    raise RuntimeError("could not find any library for {} ({})".format(libinfo, dllmsg))
RuntimeError: could not find any library for ueye_api (DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bikram/Documents/uEye/1.py", line 1, in <module>
    from pyueye import ueye
  File "/home/bikram/.local/lib/python3.8/site-packages/pyueye/__init__.py", line 56, in <module>
    from . import ueye
  File "/home/bikram/.local/lib/python3.8/site-packages/pyueye/ueye.py", line 58, in <module>
    get_dll_file, _bind = load_dll("ueye_api", ["ueye_api_64", "ueye_api"], "PYUEYE_DLL_PATH")
  File "/home/bikram/.local/lib/python3.8/site-packages/pyueye/dll.py", line 168, in load_dll
    raise ImportError(exc)
ImportError: could not find any library for ueye_api (DLL_PATH: unset)
```

**Comment by MeHow77** [comment]
I know it's quite too late for this response but I had to download libraries dedicated for Linux and then export path.
Unofficial libraries: https://github.com/anqixu/unofficial_ueye_sdk_drivers
examplary path: export PYUEYE_DLL_PATH="your/path/to/downloaded/libs"
